import './src/global.css'
import './src/normalize.css'
import './src/variables.css'
import '@fontsource/inter'
import '@fontsource/inter/400.css'
import '@fontsource/inter/500.css'
import '@fontsource/inter/600.css'
import '@fontsource/inter/700.css'
import '@fontsource/dancing-script' // Defaults to weight 400.
import '@fontsource/dancing-script/500.css'
